#!/bin/sh -e

export DESTDIR="$1"

make
(
    cd cli
    cargo build --release --locked --offline
)
make PREFIX=/usr install
mkdir -p "$1/usr/bin/"
cp target/release/tree-sitter "$1/usr/bin/tree-sitter"
