#!/bin/sh -e

#git clone https://github.com/martinus/robin-hood-hashing external/robin-hood-hashing

: > nostrip

#python3 ./scripts/update_deps.py

cmake -B build \
    -DVULKAN_HEADERS_INSTALL_DIR=/usr \
    -DSPIRV_HEADERS_INSTALL_DIR=/usr \
    -DSPIRV_TOOLS_INSTALL_DIR=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_INSTALL_INCLUDEDIR=/usr/include \
    -DCMAKE_SKIP_RPATH=True \
    -DBUILD_TESTS=OFF \
    -DBUILD_LAYER_SUPPORT_FILES=ON \
    -DBUILD_WSI_XCB_SUPPORT=ON \
    -DBUILD_WSI_XLIB_SUPPORT=ON \
    -DBUILD_WSI_WAYLAND_SUPPORT=OFF

cmake --build   build
cmake --install build
