#!/bin/sh -e

if kiss list musl; then
    sed "s/ctypes.util.find_library('c')/'libc.so'/" \
        rpython/rlib/clibffi.py > _
    mv -f _ rpython/rlib/clibffi.py

    sed -E "s~(include <unistd.h>)~\1\n# include <sys/time.h>~" \
        pypy/module/cpyext/include/Python.h > _
    mv -f _ pypy/module/cpyext/include/Python.h

    sed -E "s~(if declare_as_extern):$~\1 and name not in ['stdin', 'stdout', 'stderr']:~" \
        rpython/rtyper/lltypesystem/rffi.py > _
    mv -f _ rpython/rtyper/lltypesystem/rffi.py
fi

cd pypy/goal/
if command -v pypy2; then
    pypy2 ../../rpython/bin/rpython --opt=jit --make-jobs $(nproc) --shared targetpypystandalone
else
    python2 ../../rpython/bin/rpython --opt=jit --make-jobs $(nproc) --shared targetpypystandalone
fi
PYTHONPATH=../.. ./pypy-c ../../lib_pypy/pypy_tools/build_cffi_imports.py
cd $OLDPWD

# _ssl is currently broken
if command -v pypy2; then
    pypy2 pypy/tool/release/package.py --without-_ssl --archive-name pypy2 --targetdir .
else
    python2 pypy/tool/release/package.py --without-_ssl --archive-name pypy2 --targetdir .
fi
mkdir -p "$1/opt"
tar xvf pypy2.tar.bz2 -C "$1/opt"

mkdir -p "$1/usr/bin/"
ln -s "/opt/pypy2/bin/pypy"         "$1/usr/bin/pypy"
ln -s "/opt/pypy2/bin/pypy2"        "$1/usr/bin/pypy2"
ln -s "/opt/pypy2/bin/python2"      "$1/usr/bin/python2"
ln -s "/opt/pypy2/bin/python2.7"    "$1/usr/bin/python2.7"
ln -s "/opt/pypy2/bin/libpypy-c.so" "$1/usr/bin/libpypy-c.so"
