#!/bin/sh -e

#for patch in *.patch; do
#    patch -p1 < "$patch"
#done

sed "/#include <linux\/errqueue.h>/a #include <linux/sockios.h>" \
    linux-user/syscall.c > _ ; mv -f _ linux-user/syscall.c

# Remove bash dependency
sed 's/bash/sh/g' Makefile > _ ; mv -f _ Makefile

# The check for glib doesn't interact with our specified
# CFLAGS, so we just comandeer the ones used by configure.
# Build qemu-system* binaries dynamically linked
CONFIGURE_CFLAGS="$CFLAGS" \
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-debug-info \
    --disable-gtk \
    --disable-docs \
    --enable-sdl \
    --enable-kvm \
    --enable-pie \
    --enable-curses \
    --disable-user \
    --disable-linux-user \
    --enable-system

make
make DESTDIR="$1" PREFIX=/usr install
make clean

# Build qemu Linux user binaries statically linked.
CONFIGURE_CFLAGS="$CFLAGS" \
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-debug-info \
    --disable-gtk \
    --disable-docs \
    --disable-user \
    --enable-linux-user \
    --disable-system \
    --static

make
make DESTDIR="$1" PREFIX=/usr install

# Install the license
install -Dm755 COPYING     "$1/usr/share/LICENSES/qemu.license"
install -Dm755 COPYING.LIB "$1/usr/share/LICENSES/qemu-lib.license"
