#!/bin/sh -e

# Remove bash dependency.
sed 's/SHELL = bash -o pipefail/SHELL = sh/g' Makefile > _
mv -f _ Makefile

# The check for glib doesn't interact with our specified
# CFLAGS, so we just comandeer the ones used by configure.
# Build qemu-system* binaries dynamically linked
CONFIGURE_CFLAGS="$CFLAGS" \
    ./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-debug-info \
    --disable-gtk \
    --disable-docs \
    --enable-sdl \
    --enable-kvm \
    --enable-pie \
    --enable-curses \
    --disable-user \
    --disable-linux-user \
    --enable-system

make
make PREFIX=/usr install
make clean

# Build qemu Linux user binaries statically linked.
CONFIGURE_CFLAGS="$CFLAGS" \
    ./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-debug-info \
    --disable-gtk \
    --disable-docs \
    --disable-user \
    --enable-linux-user \
    --disable-system \
    --static

make
make PREFIX=/usr install
