#!/bin/sh -e

# Get the latest lts version from git.
version="$(curl -sL \
    https://git.alpinelinux.org/aports/plain/main/linux-lts/APKBUILD \
    | sed -n '/pkgver=/{s/pkgver=//p;q}')"

# And download the appropriate tarball.
curl -LO "https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/linux-lts-$version-r0.apk"

# This is safe to do, even with all the warnings about headers.
tar xvf ./*.apk

# Finally install the contents of the tarball.
rm -- *.apk ./.PKGINFO ./.SIGN*
cp -r . "$1"

mkdir -p "$1/etc/tinyramfs/"

# Generate a tinyramfs config.
cat - alpine.config <<EOF > "$1/etc/tinyramfs/alpine.config"

alpinever=$version-0-lts

EOF
