#!/bin/sh -e

# enable building with netbsd-curses
sed 's/tinfow tinfo/tinfow tinfo terminfo/g' \
  auto.def > _ ; mv -f _ auto.def

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --ssl \
    --sasl \
    --disable-nls \
    --disable-idn \
    --disable-doc \
    --zlib

make
make install

# Install the man pages.
# The neomutt.1 and neomuttrc.5 are usually generated (when running
# ./configure without --disable-doc) but this requires an internet
# connection (!?), so I've included them as local sources. The other
# ones are provided in the tarball.
mkdir -p \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man5"

cp -f docs/neomutt.1 \
      docs/pgpewrap.1 \
      docs/smime_keys.1 \
      "$1/usr/share/man/man1/"
cp -f docs/neomuttrc.5 \
      docs/mbox.5 \
      docs/mmdf.5 \
      "$1/usr/share/man/man5/"
