#!/bin/sh -e

# Disable stripping
: > nostrip

patch -p1 < valgrind-3.13.0-malloc.patch

# Bypass ccache
export CC="/usr/bin/cc"
export CXX="/usr/bin/c++"
export CFLAGS="$CFLAGS -fno-stack-protector -no-pie"

if [ "$(kiss owns /usr/bin/ld)" = "mold" ]; then
    lto=no
else
    lto=yes
fi

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --without-mpicc \
    --enable-lto="$lto"

make
make install
