#!/bin/sh -e
! openssl version | grep OpenSSL && {
    export NOSSL=1
}
pkg-config --exists libedit && {
    sed "s/-lreadline/-ledit/" Makefile > _
    mv -f _ Makefile
}

make
make test # Failed tests don't cause the build to fail, so it's safe to call.

mkdir -pv \
    "$1"/usr/bin/ \
    "$1"/usr/share/trealla/
cp tpl "$1"/usr/bin/tpl
cp -r library "$1"/usr/share/trealla/
