#!/bin/sh -e
! kiss list openssl && {
    export NOSSL=1
}
make
make test # Failed tests don't cause the build to fail, so it's safe to call.

mkdir -pv \
    "$DESTDIR"/usr/bin/ \
    "$DESTDIR"/usr/share/trealla/
cp tpl "$DESTDIR"/usr/bin/tpl
cp -r library "$DESTDIR"/usr/share/trealla/
