#!/bin/sh -e

dmd="$PWD/dmd/src/dmd"

mk() {
    make -f posix.mak \
        DMD="$dmd" \
        TARGET_CPU=X86 \
        RELEASE=1 \
        PIC=1 \
        $@
}

for p in patches/*; do
    patch -p0 < "$p"
done

for d in dmd druntime phobos; do
    cd "$d"
    mk
    mk install
    cd "$OLDPWD"
done

mkdir -p "$1/usr/bin/" "$1/usr/lib/" "$1/etc/" "$1/usr/include/dlang/dmd/"

cp "$dmd" "$1/usr/bin/dmd"
cat > "$1/etc/dmd.conf" <<- EOF
[Environment]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib -L--export-dynamic -fPIC
EOF

cp phobos/generated/linux/release/*/libphobos2.a "$1/usr/lib/"
cp -r phobos/*.d        "$1/usr/include/dlang/dmd"
cp -r phobos/etc        "$1/usr/include/dlang/dmd"
cp -r phobos/std        "$1/usr/include/dlang/dmd"
cp -r druntime/import/* "$1/usr/include/dlang/dmd"
chmod +x "$1/usr/bin/dmd"
