#!/bin/sh -e
for t in merge update extract perl; do
    ln -sf intltool "intltool-$t"
done
export PATH="$PWD:$PATH"

sed -e "s/as_fn_error \$? \"GNU gettext.*/echo fixed/" configure > _
mv -f _ configure
kiss list libedit && {
    sed "s/-lreadline/-ledit/" configure > _
    mv -f _ configure
}
chmod +x configure

./configure \
    --prefix=/usr
make
make install

rm -rf "$1/usr/share/locale"
rm -rf "$1/usr/share/info"
