#!/bin/sh -e

if kiss list polyml; then
    poly --script tools/smart-configure.sml
elif kiss list mosml; then
    mosml < tools/smart-configure.sml
fi

bin/build
bin/build cleanForReloc

mkdir -p "$1/opt/hol"
cp -r . "$1/opt/hol"
mkdir -p "$1/usr/bin"

for b in "/opt/hol/bin/hol" "/opt/hol/bin/hol.noquote" "/opt/hol/bin/Holmake"; do
    ln -s "$b" "$1/usr/bin/$(basename "$b")"
done
