#!/bin/sh -e

if command -v poly; then
    poly --script tools/smart-configure.sml
elif kiss list mosml; then
    mosml < tools/smart-configure.sml
fi

bin/build
bin/build cleanForReloc

mkdir -p "$1/opt/hol" "$1/usr/bin"
cp -r . "$1/opt/hol"

for b in hol hol.noquote Holmake; do
    ln -s "/opt/hol/bin/$b" "$1/usr/bin/$b"
done
