#!/bin/sh -e

sbcl --script koga \
    --reproducible-build \
    --package-path="$1" \
    --bin-path=/usr/bin/ \
    --share-path=/usr/share/clasp/ \
    --lib-path=/usr/lib/clasp/

ninja -C build
ninja -C build install
