#!/bin/sh -e

CF=""

kiss list postgresql && CF="$CF --with-pgsql"
kiss list mariadb    && CF="$CF --with-mysql"
kiss list zstd       && CF="$CF --with-zstd"

# Intended behavior
# shellcheck disable=2086
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --localstatedir=/var \
    --libexecdir=/usr/lib/dovecot \
    --with-rundir=/run/dovecot \
    --with-moduledir=/usr/lib/dovecot/modules \
    --disable-static \
    --with-sqlite \
    --with-ssldir=/etc/ssl \
    --with-zlib \
    $CF

make
make install

rm -rf "${1:?}/etc"
cp doc/mkcert.sh "${1:?}/usr/lib/dovecot/mkcert.sh"
