#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -w"

sed "s,/etc/mail,/etc/smtpd,g" usr.sbin/smtpd/smtpd.conf > _
mv -f _ usr.sbin/smtpd/smtpd.conf

./configure \
    --prefix=/usr \
    --sysconfdir=/etc/smtpd \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/smtpd \
    --with-path-mbox=/var/spool/mail \
    --with-path-empty=/var/empty \
    --with-path-socket=/run \
    --with-path-CAfile=/etc/ssl/cert.pem \
    --with-user-smtpd=smtpd \
    --with-user-queue=smtpq \
    --with-group-queue=smtpq

make
make install
