#!/bin/sh -e

export DESTDIR="$1"

sed "s/sudo//" Makefile > _
mv -f _ Makefile

make CC="$CC" destprefix="$1/usr" bootsbl
make CC="$CC" destprefix="$1/usr" BASEBOL=./bootsbl spitbol
make CC="$CC" destprefix="$1/usr" install
