#!/bin/sh -e

export DESTDIR="$1"

sed -E "s/'(true|false)'/\1/" meson_options.txt > _
mv -f _ meson_options.txt

sed "/subdir('po')/d" meson.build > _
mv -f _ meson.build

meson setup \
    -Dprefix=/usr \
    -Ddoxygen=false \
    -Dman=false \
    -Dtests=false \
    -Ddatabase='simple' \
    -Dgtk=disabled \
    output

ninja -C output
ninja -C output install
