#!/bin/sh -e

for f in gnu-apl.d/preferences gnu-apl.d/preferences.in; do
    sed \
        -e '64 s/^.*Color.*ANSI/#&/' \
        -e '65 s/^#.*Color.*CURSES/Color\tCURSES/' "$f" > _
    mv -f _ "$f"
done

ed src/Error.hh << EOF
/#include "UCS_string.hh"/
a

#include <cstring>
.
w
q
EOF

export CFLAGS="-std=gnu99 $CFLAGS"
CXX_WERROR='no' \
    ./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make PREFIX=/usr
make PREFIX=/usr install
