#!/bin/sh -e

for f in gnu-apl.d/preferences gnu-apl.d/preferences.in; do
    sed \
        -e '64 s/^.*Color.*ANSI/#&/' \
        -e '65 s/^#.*Color.*CURSES/Color\tCURSES/' "$f" > _
    mv -f _ "$f"
done

sed "1i#include <cstring>" src/Error.hh > _
mv -f _ src/Error.hh

export CFLAGS="-std=gnu99 $CFLAGS"
CXX_WERROR='no' \
    ./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make PREFIX=/usr
make PREFIX=/usr install
