#!/bin/sh -e

sed -e '/"po\/Makefile") CONFIG_FILES=/d' \
    -e "s~po/Makefile~~" configure > _
mv -f _ configure
chmod +x configure

# CXXFLAGS is propagated to /etc/R/Makeconf that is read when building
# additional R modules. -D__MUSL__ is needed for some modules like Rcpp.
# htps://github.com/RcppCore/Rcpp/issues/448
export CXXFLAGS="$CXXFLAGS -D__MUSL__"
#export CFLAGS="$CFLAGS"

rm -rf po

# R refuses to build without these files which is weird considering that
# they are not included in the source tarball
(
    cd doc
    touch NEWS.rds
    touch NEWS.2.rds
    touch NEWS.3.rds
)

conf_flags=""
for p in cairo lapack libpng libtiff-4 tk blas libjpeg x11; do
    if pkg-config --exists $p; then
        case $p in
            x11)       conf_flags="$conf_flags --with-x";;
            tk)        conf_flags="$conf_flags --with-tcltk";;
            libtiff-4) conf_flags="$conf_flags --with-tiff";;
            libjpeg)   conf_flags="$conf_flags --with-jpeglib";;
            *)         conf_flags="$conf_flags --with-$p";;
        esac
    fi
done

# Intended Behavior.
# shellcheck disable=2086
./configure \
    --prefix=/usr \
    --sysconfdir=/etc/R \
    --localstatedir=/var \
    --libdir=/usr/lib \
    rhome=/usr \
    rdocdir=/usr/share/doc/R \
    rincludedir=/usr/include/R \
    rsharedir=/usr/share/R \
    --disable-nls \
    --enable-R-shlib \
    --disable-java \
    --with-recommended-packages \
    --without-ICU \
    --without-docs \
    $conf_flags \
    gcc=gfortran \
    LIBnn=Lib

make DESTDIR=""
make DESTDIR="$1" install

# Install libRmath.so.
make -C src/nmath/standalone
make DESTDIR="$1" -C src/nmath/standalone install

# Fixup R wrapper script (taken from Arch).
ln -sf "/usr/bin/R" "$1/usr/lib/R/bin/R"

# Remove some useless files (COPYING is duplicated, it will be
# in -doc, don't worry).
rm "$1/usr/lib/R/COPYING" "$1/usr/lib/R/SVN-REVISION"

rm -rf "$1/usr/lib/R/library/translations"
rm -rf "$1/usr/share/R/licenses"
rm -rf "$1/usr/share/doc"
