#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_DOXYGEN=OFF \
    -DWITH_SWIG=OFF \
    -DWITH_PYTHON=OFF

cmake --build   build
cmake --install build
