#!/bin/sh -e

export AS="cc -c"
export ASPP="cc -c"

for patch in *.patch; do
    patch -p1 < "$patch"
done

./configure \
    --prefix /usr \
    --bindir /usr/bin \
    --libdir /usr/lib/ocaml \
    --mandir /usr/share/man \
    --disable-force-safe-string \
    --with-pic

make world.opt
make install

find "$1/usr/lib/ocaml" \
    \( -name '*.cmt' -o -name '*.cmti' -o -name '*.ml' \) \
    -a -delete

# Uncomment if you don't want the compiler libraries.
# rm -rf "$1/usr/lib/ocaml/compiler-libs"
