#!/bin/sh -e

:> nostrip

# ccl segfaults if we don't append this flag.
for f in lisp-kernel/*/Makefile
do
    sed -E "s/^(OSLIBS .*)/\1 -no-pie/" "$f" > _
    mv -f _ "$f"
done

kiss l glibc || {

# musl fixes

# Define _libc_xmmreg if we are not on glibc.
ed lisp-kernel/lisp-debug.c >/dev/null <<EOF
36a
#ifndef __GLIBC__
struct _libc_xmmreg {
  unsigned int element[4];
};
#endif
.
w
q
EOF

# Remove mcheck.h include.
# Wrap glibc function call in ifdefs
ed lisp-kernel/pmcl-kernel.c <<EOF
/#include <mcheck.h>/
d
/LispObj fs_addr = 0L, gs_addr = 0L, cur_thread = (LispObj)pthread_self();/
a
#ifdef __GLIBC__
.
/char *gnu_get_libc_version(void);/
a
#else
#define gnu_get_libc_version() ""
#endif
.
w
q
EOF

# Glibcisms are not Linuxisms.
sed "185s/LINUX/__GLIBC__/" lisp-kernel/thread_manager.c > _
mv -f _ lisp-kernel/thread_manager.c

# Delete include of fpu_control.h as musl doesn't have this header.
sed "/#include <fpu_control.h>/d" lisp-kernel/x86-exceptions.c > _
mv -f _ lisp-kernel/x86-exceptions.c

}

(
    cd lisp-kernel/linuxx8664
    make clean
    make -j1
)

./lx86cl64 -n -Q -b -e '(ccl:rebuild-ccl :full t)' -e '(ccl:quit)'

find . -type d -name .svn -exec rm -rf '{}' +
find . -name '*.o' -delete
find . -name '*.*fsl' -delete

mkdir -p \
    "$1/usr/lib/ccl/" \
    "$1/usr/bin/"
cp -r lx86cl64 "$1/usr/lib/ccl/"
cp lx86cl64.image "$1/usr/lib/ccl/"

cat > "$1/usr/bin/ccl" <<EOF
#!/bin/sh
exec /usr/lib/ccl/lx86cl64 \$@
EOF
chmod +x "$1/usr/bin/ccl"

for d in lib library scripts tools xdump
do
    cp -r "$d" "$1/usr/lib/ccl/"
done

mkdir -p "$1/usr/share/examples/ccl"
cp -r examples/* "$1/usr/share/examples/ccl"
