#!/bin/sh -e

ownsdir(){
    ! [ "$(whoami)" != "$(stat -c "%U" "$1")" ]
}

pkgd="$(KISS_HOOK='' kiss s "$2" | sed q)"
m="/tmp/kiss-lang-hook-$2"
kiss l git-extras 1>/dev/null 2>&1 || exit 0

mod(){
    cd "$pkgd"
    if git rev-parse ; then
        if ownsdir "$pkgd" ; then
            if ! [ -e "$m" ] ; then
                $1 ; touch "$m"
            fi
        else
            if ! [ -e "$m" ] ; then
                $2 ; touch "$m"
            fi
        fi
    fi
}

case $1 in
    pre-source)
        case $2 in
            gcc)
                # Enables gfortran & gdc.
                f(){
                    sed -E -i "s/(c,c\+\+)/\1,fortran,d/" build
                }
                sf(){
                    $KISS_SU sed -E -i "s/(c,c\+\+)/\1,fortran,d/" build
                }
                mod f sf
                ;;
        esac
    ;;
    pre-build)
        rm -- "$m"
    ;;
    post-install)
        cd "$pkgd"
        if git rev-parse ; then
            if ownsdir "$pkgd" ; then
                git-clear -f
            else
                $KISS_SU git-clear -f
            fi
        fi
    ;;
esac

