#!/bin/sh -e

ownsdir(){
    ! [ "$(whoami)" != "$(stat -c "%U" "$1")" ]
}

pkgd="$(KISS_HOOK='' kiss s "$2" | sed q)"
m="/tmp/kiss-lang-hook-$2"
kiss l git-extras 1>/dev/null 2>&1 || exit 0

case $1 in
    pre-source)
        case $2 in
            gcc)
                # Enables gfortran & gdc.
                (
                cd "$pkgd"
                if git rev-parse ; then
                    if ownsdir "$pkgd" ; then
                        if ! [ -e "$m" ] ; then
                            sed -E -i "s/(c,c\+\+)/\1,fortran,d/" build
                            touch "$m"
                        fi
                    else
                        if ! [ -e "$m" ] ; then
                            $KISS_SU sed -E -i "s/(c,c\+\+)/\1,fortran,d/" build
                            touch "$m"
                        fi
                    fi
                fi
                )
                ;;
        esac
    ;;
    post-install)
        (
        cd "$pkgd"
        if git rev-parse ; then
            if ownsdir "$pkgd" ; then
                git-clear -f
            else
                $KISS_SU git clear -f
            fi
        fi
        )
        rm -- "$m"
    ;;
esac

