#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=FALSE \
    -DOIIO_BUILD_TESTS=OFF \
    -DBUILD_MISSING_FMT=OFF \
    -DCMAKE_SKIP_RPATH=ON \
    -DSTOP_ON_WARNING=OFF \
    -DUSE_EXTERNAL_PUGIXML=ON \
    -DUSE_PYTHON=OFF \
    -DINSTALL_FONTS=OFF \
    -Wno-dev

cmake --build   build
cmake --install build
