#!/bin/sh -e

export DESTDIR="$1"

rm -Rf src/foreign/libffi

cd src

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-shared \
    --disable-strip \
    --disable-docs \
    --enable-jit

make
make install
