#!/bin/sh -e

export DESTDIR="$1"

export PATH="$PATH:core/bin"

cv=$(crystal -v | sed -n -E "/^Crystal/s/^.* ([0-9\.]+).*$/\1/p")
export CRYSTAL_CONFIG_VERSION="$cv"
export EXPORT_CC="CC=cc"

make crystal \
    CRYSTAL_CONFIG_PATH="/usr/lib/crystal" \
    CRYSTAL_CACHE_DIR=".tmp/crystal" \
    LLVM_CONFIG="/usr/bin/llvm-config" \
    release=1 \
    static=1 \
    FLAGS="--no-debug" \
    CRYSTAL_PATH="src"

mkdir -p "$1/usr/bin"
cp .build/crystal "$1/usr/bin/crystal"

mkdir -p "$1/usr/lib"
cp -a src "$1/usr/lib/crystal"
