#!/bin/sh -e

for sml in mlton mlkit poly mosml; do
    if command -v $sml; then
        make with-$sml
        break
    fi
done

make INSTALLDIR="$1/opt/hamlet" install

mkdir -p "$1/usr/bin/"
cat << EOF > "$1/usr/bin/hamlet"
#!/bin/sh
/opt/hamlet/hamlet \$@
EOF
chmod +x "$1/usr/bin/hamlet"
