#!/bin/sh -e

export DESTDIR="$1"

unzip ./*.zip
cd "S$2/"

patch -p1 < ../ccl-and-ecl-support.patch

mkdir -p "$1/usr/bin/"
for lisp in sbcl ccl clisp; do
    case "$lisp" in
        clisp)
            "$lisp" install.lsp
            ;;
        *)
        "$lisp" --load install.lsp
        ;;
    esac
    cp "$lisp-shen.exe" "$1/usr/bin/shen-$lisp"
done
