#!/bin/sh -e

# Fix LDFLAGS, courtesy of Arch Linux
sed -i -E "s~^EXTLDFLAGS.*~EXTLDFLAGS  = \$(shell pkg-config --libs webkit2gtk-webextension-4.0) -shared~" config.mk

# Chnage the follow hints from numbers to letters on the home row
sed -i -E "s~(setting_add\(c, \"hint-keys\", TYPE_CHAR, &\")0123456789~\1asdfghjkl~" src/setting.c

make PREFIX=/usr
make DESTDIR=$1 PREFIX=/usr install
