#!/bin/sh -e

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man

# Rules: build_all -> build w/o timing, install_notiming -> install w/o timing
make -j1 build_all
make -j1 install_notiming
