#!/bin/sh -e

if pkg-config --exists libedit; then
    sed "s/-lreadline/-ledit/" configure > _
    mv -f _ configure
    chmod +x configure
fi

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man

# Rules: build_all -> build w/o timing, install_notiming -> install w/o timing
make -j1 build_all
make -j1 install_notiming
