#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --enable-single-binary=symlinks \
    --with-packager="$(grep '^NAME="' /etc/os-release | cut -d'"' -f2)" \
    --without-libgmp \
    --disable-libcap \
    --disable-nls

make
make install
