#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -I/usr/include/tirpc/"

cd gcl

# Fix memalign.
sed "/GNUMALLOC/s/ifndef/ifdef/" o/alloc.c > _
mv -f _ o/alloc.c

# Remove info pages.
rm -rf info
sed "/pargcl_all/s/do-info//" makefile > _
mv -f _ makefile

setarch linux64 -R \
    sh configure \
    --prefix=/usr \
    --enable-notify=no \
    --enable-dynsysgmp \
    --disable-xdr

make -j1
make install
