#!/bin/sh -e
patch -p0 -i "picker-2.2.patch"
install -Dm755 -t "$1/usr/bin" fff;
install -Dm644 -t "$1/usr/share/man/man1" fff.1;
install -Dm644 -t "$1/usr/share/licenses/fff" LICENSE.md;
install -Dm644 -t "$1/usr/share/doc/fff" README.md
