#!/bin/sh -e

read -r ver _ < "${0%/*}/version"

KMVER=${ver%%.*}
KmVER=${ver#*.}
KmVER=${KmVER%%.*}
KpVER=${ver##*.}

patch -p1 < kernel-no-perl.patch

# Kernel versions greater than 5.12 have this issue
if [ "$KMVER" -ge 5 ] && [ "$KmVER" -gt 12 ]; then
    sed '/<stdlib.h>/a #include <linux/stddef.h>' \
        tools/objtool/arch/x86/decode.c > _
    mv -f _ tools/objtool/arch/x86/decode.c
fi

cp config .config

# Only ld.bfd and ld.lld are supported.
for linker in ld.bfd ld.lld; do
    if command -v "$linker"; then
        ln -s "$(command -v "$linker")" ld
        break
    fi
done
export PATH="$PWD:$PATH"

make olddefconfig # Update the provided config.

make -j"$(nproc)"  # Force build with all cores.

mkdir -pv "$1/boot"
install -Dm644 "arch/x86/boot/bzImage" "$1/boot/vmlinuz-$ver"
install -Dm644 "System.map"            "$1/boot/System.map-$ver"
install -Dm644 ".config"               "$1/boot/Config-$ver"
