#!/bin/sh -e

(   
    cd HOL
    if kiss list polyml; then
        poly --script tools/smart-configure.sml
    elif kiss list mosml; then
        mosml < tools/smart-configure.sml
    fi
    bin/build
)

# This will take a LONG time.
HOL/bin/Holmake
