#!/bin/sh -e

mk() {
    make \
        PREFIX=/usr \
        USE_OPENMP=0 \
        NO_LAPACK=0 \
        NO_AFFINITY=1 \
        NO_STATIC=1 \
        INTERFACE64=1 \
        NUM_THREADS="$(nproc)" \
        MAJOR_VERSION=3 \
        "$@"
}

CFLAGS='' mk CFLAGS="$CPPFLAGS $CFLAGS"
mk install

# Create symlinks so it can be swapped via `kiss alt`.
ln -s /usr/lib/libopenblas.so        "$1/usr/lib/libblas.so"
ln -s /usr/lib/libopenblas.so.3      "$1/usr/lib/libblas.so.3"
ln -s /usr/lib/pkgconfig/openblas.pc "$1/usr/lib/pkgconfig/blas.pc"
