#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

patch -p1 < pkcs7-fix.patch
kiss list libX11 && x11="yes"

make \
    prefix="/usr" \
    DESTDIR="$1" \
    USE_SYSTEM_LIBS="yes" \
    HAVE_X11="${x11:-no}" \
    HAVE_GLUT=no \
    install
