#!/bin/sh -e

read -r ver _ < "${0%/*}/version"
echo "\"${ver}\"" > version.lisp-expr

# If you already have sbcl installed, build
# with sbcl instead, as it will be much faster
if kiss l sbcl 1> /dev/null 2> /dev/null
then
	./make.sh --xc-host=sbcl --prefix=/usr
else
	./make.sh --xc-host=ecl --prefix=/usr
fi
INSTALL_ROOT="$1/usr" ./install.sh
