#!/bin/sh -e

read -r ver _ < "${0%/*}/version"
echo "\"${ver}\"" > version.lisp-expr

# If you already have sbcl installed, build with sbcl instead.
if kiss list sbcl; then
    ./make.sh --xc-host=sbcl --prefix=/usr
elif kiss list ccl; then
    ./make.sh --xc-host=ccl --prefix=/usr
elif kiss list clisp; then
    ./make.sh --xc-host=clisp --prefix=/usr
else
    ./make.sh --xc-host=ecl --prefix=/usr
fi
INSTALL_ROOT="$1/usr" ./install.sh
