#!/bin/sh -e

export DESTDIR="$1"

make CC="${CC:-cc}" \
    MYCFLAGS="$CFLAGS -fPIC" \
    MYLDFLAGS="$LDFLAGS" \
    posix

sed "s/install -p/install/" Makefile > _
mv -f _ Makefile

make \
    INSTALL_TOP="$1/usr" \
    INSTALL_MAN="$1/usr/share/man/man1" \
    INSTALL_DATA="cp -P" \
    install

# Generate pkgconfig file on the fly.
mkdir -p "$1/usr/lib/pkgconfig/"
cat > "$1/usr/lib/pkgconfig/lua.pc" << EOF
V=${2%.*}
R=$2

prefix=/usr
INSTALL_BIN=\${prefix}/bin
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
INSTALL_MAN=\${prefix}/man/man1
INSTALL_LMOD=\${prefix}/share/lua/\${V}
INSTALL_CMOD=\${prefix}/lib/lua/\${V}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: \${R}
Requires:
Libs: -L\${libdir} -llua -lm
Cflags: -I\${includedir}
EOF
