#!/bin/sh -e

cd harec
cp configs/linux.mk config.mk
sed "s~/local~~" config.mk > _
mv -f _ config.mk

make
make install
cd "$OLDPWD"

export PATH="$1/usr/bin/:$PATH"

sed "s:/usr/local:/usr:" configs/linux.mk > config.mk

LOCALVER=arch make -j1

make DESTDIR="$1" install
