#!/bin/sh -e

cat <<EOF
Here are some commands to get you started.

For a debian sid chroot:

# debootstrap --no-check-gpg --arch=amd64 sid sid-chroot http://deb.debian.org/debian/

For a release of ubuntu chroot:

# debootstrap --no-check-gpg --arch=amd64 jammy jammy-chroot http://archive.ubuntu.com/ubuntu/

You can check the following websites for the actual releases:
Ubuntu: http://archive.ubuntu.com/ubuntu/dists/
Debian: http://deb.debian.org/debian/dists/

EOF
