#!/bin/sh -e

# shellcheck disable=SC2155

export LUAJIT_LIB="$(pkgconf --variable=libdir luajit)"
export LUAJIT_INC="$(pkgconf --variable=includedir luajit)"

./configure \
    --prefix=/var/lib/nginx \
    --sbin-path=/usr/bin/nginx \
    --modules-path=/usr/lib/nginx/modules \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/var/run/nginx/nginx.pid \
    --lock-path=/var/run/nginx/nginx.lock \
    --http-client-body-temp-path=/var/lib/nginx/tmp/client_body \
    --http-proxy-temp-path=/var/lib/nginx/tmp/proxy \
    --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi \
    --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi \
    --http-scgi-temp-path=/var/lib/nginx/tmp/scgi \
    --with-perl_modules_path=/usr/lib/perl5/vendor_perl \
    --user=nginx \
    --group=nginx \
    --with-threads \
    --with-file-aio \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_image_filter_module=dynamic \
    --with-http_geoip_module=dynamic \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_auth_request_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_degradation_module \
    --with-http_slice_module \
    --with-http_stub_status_module \
    --with-http_perl_module=dynamic \
    --with-mail=dynamic \
    --with-mail_ssl_module \
    --with-stream=dynamic \
    --with-stream_ssl_module \
    --with-stream_realip_module \
    --with-stream_geoip_module=dynamic \
    --with-stream_ssl_preread_module 

make
make DESTDIR="$1" install

install -Dm644 objs/nginx.8 "$1/usr/share/man/man8/nginx.8"
install -Dm644 nginx.conf "$1/etc/nginx/nginx.conf"
install -Dm755 nginx.initd "$1/etc/init.d/nginx"
install -Dm644 nginx.confd "$1/etc/conf.d/nginx"
install -Dm644 nginx.logrotate "$1/etc/logrotate.d/nginx"
install -Dm644 default.conf "$1/usr/share/nginx/http-default_server.conf"
install -Dm644 stream.conf "$1/etc/nginx/stream.conf"

mkdir -p "$1/etc/nginx/stream.d"
