#!/bin/sh -e

# Install config with default http server to new location (since 1.18.0-r13).
if ! [ -e /etc/nginx/http.d/default.conf ]; then
    install -m644 /usr/share/nginx/http-default_server.conf \
        /etc/nginx/http.d/default.conf
fi

if ! [ -e /etc/nginx/conf.d ]; then
    # Symlink conf.d to http.d for backward compatibility.
    ln -s http.d /etc/nginx/conf.d
fi

exit 0
