#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON

cmake --build   build
cmake --install build
rm "$1/usr/include/zip.h" "$1/usr/include/unzip.h"
