#!/bin/sh -e

export DESTDIR="$1"

sed "/__USE_FILE_OFFSET64/s/_FILE_OFFSET_BITS == 64/false/" \
    druntime/src/core/sys/posix/config.d > _
mv -f _ druntime/src/core/sys/posix/config.d

for p in patches/*; do
    patch -p0 < "$p"
done

dmd="$PWD/dmd/src/dmd"

mk() {
    # False positive.
    # shellcheck disable=2068
    make -f posix.mak DMD="$dmd" TARGET_CPU=X86 RELEASE=1 PIC=1 $@
}

mk -C dmd
mk -C druntime
mk -C phobos

mkdir -p "$1/usr/bin/" "$1/usr/lib/" "$1/etc/" "$1/usr/include/dlang/dmd/" "$1/usr/share/man/man1"  "$1/usr/share/man/man5"

cp "$dmd" "$1/usr/bin/dmd"
cat > "$1/etc/dmd.conf" <<- EOF
[Environment]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib -L--export-dynamic -fPIC
EOF

cp dmd/docs/man/man1/*  "$1/usr/share/man/man1"
cp dmd/docs/man/man5/*  "$1/usr/share/man/man5"
cp phobos/generated/linux/release/*/libphobos2.a "$1/usr/lib/"
cp -r phobos/*.d        "$1/usr/include/dlang/dmd"
cp -r phobos/etc        "$1/usr/include/dlang/dmd"
cp -r phobos/std        "$1/usr/include/dlang/dmd"
cp -r druntime/import/* "$1/usr/include/dlang/dmd"
chmod +x "$1/usr/bin/dmd"
