#!/bin/sh -e

if ! patch --help 2>&1 | grep gnu; then
    echo "Switch to gnu patch:"
    echo "# kiss a patch /usr/bin/patch"
    exit 1
fi

if command -v mlton; then
    make -j1 all
else
    make -j1 bootstrap-polyml
fi
make PREFIX=/usr DESTDIR="$1" install
