#!/bin/sh -e

cet="https://github.com/llvm/llvm-project/releases/download/llvmorg-VERSION/clang-tools-extra-VERSION.src.tar.xz tools/extra"

ownsdir(){
    ! [ "$(whoami)" != "$(stat -c "%U" "$1")" ]
}

pkgd="$(KISS_HOOK='' kiss s "$2" | sed q)"
m="/tmp/kiss-lsp-hook-$2"
kiss l git-extras 1>/dev/null 2>&1 || exit 0

case $1 in
    pre-source)
        case $2 in
            clang)
                (
                cd "$pkgd"
                if git rev-parse ; then
                    if ownsdir "$pkgd" ; then
                        if ! [ -e "$m" ] ; then
                            echo "$cet" >> sources
                            KISS_HOOK='' kiss c
                            touch "$m"
                        fi
                    else
                        if ! [ -e "$m" ] ; then
                            $KISS_SU sh -c "echo \"$cet\" >> sources"
                            $KISS_SU sh -c "KISS_HOOK='' kiss c"
                            touch "$m"
                        fi
                    fi
                fi
                )
                ;;
            rust)
                (
                cd "$pkgd"
                if git rev-parse ; then
                    if ownsdir "$pkgd" ; then
                        if ! [ -e "$m" ] ; then
                            sed -E -i "s/(\"cargo\")/\"rls\", \1/" build
                            touch "$m"
                        fi
                    else
                        if ! [ -e "$m" ] ; then
                            $KISS_SU sed -E -i "s/(\"cargo\")/\"rls\", \1/" build
                            touch "$m"
                        fi
                    fi
                fi
                )
                ;;
        esac
    ;;
    post-install)
        (
        cd "$pkgd"
        if git rev-parse ; then
            if ownsdir "$pkgd" ; then
                git-clear -f
            else
                $KISS_SU git-clear -f
            fi
        fi
        )
        rm -- "$m"
    ;;
esac

