#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --disable-gsl \
    --disable-mathlib \
    --disable-mpfr \
    --disable-plotutils \
    --disable-postgresql

make -j1
make -j1 install
