#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --disable-gsl \
    --disable-mathib \
    --disable-mpfr \
    --disable-plotutils \
    --disable-postgresql

make
make install
