#!/bin/sh -e

# shellcheck disable=2155

export DESTDIR="$1"

export CFLAGS="$CFLAGS $(pkg-config --cflags minizip-ng)"
export CXXFLAGS="$CXXFLAGS $(pkg-config --cflags minizip-ng)"
export LDFLAGS="$LDFLAGS $(pkg-config --libs minizip-ng)"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DOCIO_BUILD_TESTS=OFF \
    -DOCIO_BUILD_GPU_TESTS=OFF \
    -DOCIO_USE_SSE=TRUE

cmake --build   build
cmake --install build
