#!/bin/sh -e

# shellcheck disable=2155

export DESTDIR="$1"

if find . -name '*.patch' | grep patch; then
    for patch in *.patch; do
        patch -p1 < "$patch"
    done
fi

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DOCIO_BUILD_TESTS=OFF \
    -DOCIO_BUILD_GPU_TESTS=OFF \
    -DOCIO_USE_SSE=TRUE

cmake --build   build
cmake --install build
