#!/bin/sh -e

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DVULKAN_HEADERS_INSTALL_DIR=/usr \
    -DBUILD_WSI_WAYLAND_SUPPORT=OFF

cmake --build   build
cmake --install build
