#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc/geoip \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info

make
make DESTDIR="$1" install

mkdir -p "$1/usr/share/GeoIP"
