#!/bin/sh -e

sed "s/tests testsuite//" Makefile.am > _
mv -f _ Makefile.am

sed "s/AtkObject/GObject/" \
    ./gtksourceview/gtksourcestyleschemechooserwidget.c > _
mv -f _ ./gtksourceview/gtksourcestyleschemechooserwidget.c

# error when building gummi

#/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/12.2.0/../../../../lib/libgtksourceview-3.0.so: undefined reference to `atk_object_set_name'
#/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/12.2.0/../../../../lib/libgtksourceview-3.0.so: undefined reference to `gtk_widget_get_accessible'


autoreconf -vif

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-nls \
    --disable-gtk-doc-html

make
make DESTDIR="$1" install
