#!/bin/sh -e

export DESTDIR="$1"

v="$(ghc --numeric-version)"

if ! command -v cabal; then
    ./bootstrap/bootstrap.py \
        -d "./bootstrap/linux-$v.json" \
        -w /usr/bin/ghc
    export PATH="$PWD/_build/bin:$PATH"
fi

# Statically build cabal.
cabal v2-build cabal \
    --enable-static \
    --enable-executable-static

mkdir -p "$1/usr/bin"
cp "$(find dist-newstyle/ -type f -name cabal)" "$1/usr/bin/"
