#!/bin/sh -e

export DESTDIR="$1"

v="$(ghc --numeric-version | cut -d'.' -f1-2)"

if ! command -v cabal; then
    bootfile="$(find bootstrap/ -name "*$v*")"
    ./bootstrap/bootstrap.py \
        -d "$bootfile" \
        -w /usr/bin/ghc
    export PATH="$PWD/_build/bin:$PATH"
fi

# Statically build cabal.
cabal v2-build cabal \
    --enable-static \
    --enable-executable-static

mkdir -p "$1/usr/bin"
cp "$(find dist-newstyle/ -type f -name cabal)" "$1/usr/bin/"
