#!/bin/sh -e

# This hook adds `clangd` and `rls` as executables for the clang and rust pkgs.
# Needs `kw`.
case $1 in
    clang)
        ver="$(cut -d' ' -f1 < "$2/version")"
        cte="https://github.com/llvm/llvm-project/releases/download/llvmorg-$ver/clang-tools-extra-$ver.src.tar.xz tools/extra"
        echo "$cte" >> "$2/sources"
        (
            cd "$2"
            KISS_HOOK='' kiss checksum
        )
        ;;
    rust) sed -E -i "s/(\"cargo\")/\"rls\", \1/" "$2/build";;
esac
