#!/bin/sh -e

makefile=makefile.linux_amd64_asm

cp "$makefile" makefile.machine

sed -e "s,g++,${CXX:-c++}," \
    -e "s,gcc,${CC:-cc}," \
    makefile.machine > _
mv -f _ makefile.machine

make all3 OPTFLAGS="$CFLAGS"

make install \
    DEST_DIR="$1" \
    DEST_HOME=/usr \
    DEST_MAN=/usr/share/man
