#!/bin/sh -e

cd App*/

sed -e "/subdir('po/d" \
    -e "/subdir('docs/d" \
    meson.build > _
mv -f _ meson.build

meson setup \
    -Dprefix=/usr \
    -Dapidocs=false \
    -Dcompose=false \
    -Ddocs=false \
    -Dqt=false \
    -Dvapi=false \
    -Dinstall-docs=false \
    -Dstemming=false \
    -Dapt-support=false \
    -Dgir=false \
    output

ninja -C output
ninja -C output install
