#!/bin/sh -e
./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --libexecdir=/usr/libexec \
    --enable-sbcl \
    --with-default-lisp=sbcl

make
make emacsdir=/usr/share/emacs/site-lisp/maxima install
