#!/bin/sh -e

export DESTDIR="$1"

sed "/__USE_FILE_OFFSET64/s/_FILE_OFFSET_BITS == 64/false/" \
    dmd/druntime/src/core/sys/posix/config.d > _
mv -f _ dmd/druntime/src/core/sys/posix/config.d

case "$(readlink "$(command -v ld)")" in
    ld.bfd) ;;
    ld.gold) ;;
    *)
    echo "Only 'ld' from 'binutils' is supported"
    exit 1
    ;;
esac

export LDFLAGS="$LDFLAGS -lpthread"

if [ -e patches/ ]; then
    for p in patches/*; do
        patch -p0 < "$p"
    done
fi

dmd="$(command -v dmd)"

mk() {
    # False positive.
    # shellcheck disable=2068
    make -f posix.mak TARGET_CPU=X86 ENABLE_RELEASE=1 $@
}

HOST_DMD="$dmd" dmd -run ./dmd/compiler/src/build.d
make -C dmd/compiler/docs

case "$(uname -m)" in
    x86_64) _arch=64 ;;
    i*86)   _arch=32 ;;
esac

dmd="$PWD/dmd/generated/linux/release/$_arch/dmd"

mk -C dmd/druntime
mk -C phobos

mkdir -p "$1/usr/bin/" "$1/usr/lib/" "$1/etc/" "$1/usr/include/d" "$1/usr/include/d/druntime" "$1/usr/share/man/man1"  "$1/usr/share/man/man5"
cp "$dmd" "$1/usr/bin/dmd"
cat > "$1/etc/dmd.conf" <<- EOF
[Environment]
DFLAGS=-I/usr/include/d -I/usr/include/d/druntime/import -L-L/usr/lib -L-L/usr/lib -L--no-warn-search-mismatch -L--export-dynamic -fPIC
EOF

cp dmd/generated/docs/man/man1/* "$1/usr/share/man/man1"
cp dmd/generated/docs/man/man5/* "$1/usr/share/man/man5"
cp phobos/generated/linux/release/*/libphobos2.a "$1/usr/lib/"
cp dmd/generated/linux/release/*/libdruntime.a   "$1/usr/lib"
cp -r phobos/*.d            "$1/usr/include/d"
cp -r phobos/etc            "$1/usr/include/d"
cp -r phobos/std            "$1/usr/include/d"
cp -r dmd/druntime/import   "$1/usr/include/d/druntime"
chmod +x "$1/usr/bin/dmd"
