#!/bin/sh -e

patch -p1 < mu-utils-stdout.patch

# Disable tests.
find . -type f -name meson.build -exec sed -i "/subdir('tests')/d" {} \;

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install
