#!/bin/sh -e

# Disable tests.
for f in $(find . -type f -name meson.build); do
    sed "/subdir('tests')/d" "$f" > _
    mv -f _ "$f"
done

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install
