#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Remove libcap dependency (used solely when bwrap is suid root).
# User namespaces are better - should be used in place of libcap and are free.
sed 's/as_fn_error.*libcap/: "/g'        configure > _
mv -f _ configure
sed 's/as_fn_error.*capability\.h/: "/g' configure > _
mv -f _ configure

# Remove fuse2 dependency (used solely w/ root "system-helper" daemon for file transfer.
# Unneeded in our case and drops the old fuse version.
sed 's/as_fn_error.*fuse/: "/g' configure > _
mv -f _ configure

# Turn the fuse2 filesystem into a C program which does nothing.
# This is the easiest way to "turn off" revokefs as there's no official support for doing so.
cat << EOF > revokefs/main.c
int main() { return 0; }
EOF
: > revokefs/writer.c

chmod +x configure
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --without-systemd \
    --disable-system-helper \
    --disable-nls \
    --disable-seccomp \
    --disable-sandboxed-triggers \
    --disable-documentation \
    --disable-introspection \
    --with-priv-mode=none

make
make install

# Remove dbus/systemd/libraries (unneeded stuff).
# This is a dumb warning which appears only when /usr/share does.
# shellcheck disable=2115
{
    rm -rf "$1/etc"
    rm -rf "$1/usr/share"
    rm -rf "$1/usr/lib"
    rm -rf "$1/usr/include"
    rm  -f "$1/usr/libexec/revokefs-fuse"
}
