#!/bin/sh -e

export DESTDIR="$1"

rm -Rf src/foreign/libffi

if command -v scheme; then
    scheme_cfg="--enable-scheme=$(command -v scheme)"
fi

cd src

# Intended.
# shellcheck disable=2086
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-shared \
    ${scheme_cfg:-} \
    --disable-docs

make
make install

rm -Rf "$1/usr/share/applications"
rm -Rf "$1/usr/lib/racket/gracket"
