#!/bin/sh -e

# Fix issues with musl and firefox.
# https://bugs.freedesktop.org/show_bug.cgi?id=35268
# https://github.com/mesa3d/mesa/commit/9f37c9903b87f86a533bfaffa72f0ecb285b02b2
# https://gitlab.freedesktop.org/mesa/mesa/-/issues/966
sed "/pre_args += '-DUSE_ELF_TLS'/d" meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd > /dev/null 2>&1 || glvnd_enabled=false

pkg-config --exists valgrind > /dev/null 2>&1 || valgrind=false

pkg-config --exists wayland-protocols && platforms=x11,wayland

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms="${platforms:-x11}" \
    -Dgallium-drivers=radeonsi \
    -Dvulkan-drivers=amd \
    -Dvulkan-layers=device-select,intel-nullhw,overlay \
    -Dglx=auto \
    -Degl=enabled \
    -Dvalgrind="${valgrind:-false}" \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-false}" \
    output

ninja -C output
meson install -C output
