#!/bin/sh -e

export DESTDIR="$1"

# rust_std is not (yet?) supported by muon, and we should try
# to avoid a hard rust dependency here if possible.
sed "/rust_std=2021/d" meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd || glvnd_enabled=false

pkg-config --exists valgrind || valgrind=false

pkg-config --exists wayland-protocols && platforms=x11,wayland

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms="${platforms:-x11}" \
    -Dgallium-drivers=radeonsi \
    -Dglx=auto \
    -Degl=enabled \
    -Dvalgrind="${valgrind:-false}" \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-true}" \
    -Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc \
    -Dllvm=enabled \
    -Dvulkan-drivers=amd \
    -Dvulkan-layers=device-select,intel-nullhw,overlay \
    output

ninja -C output
meson install -C output
