#!/bin/sh -e

# 'Build' msbuild.
(
    cd msbuild
    ar vx *.deb
    tar xf data.tar.xz
    mkdir -p ../junk/usr
    cp -r usr/ ../junk
)

export PATH="$PWD/junk/bin:$PATH"

mk() {
    make monocmd=/usr/bin/mono prefix=/usr $@
}
mk
mk install
