#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -D_LARGEFILE64_SOURCE"
export CXXFLAGS="$CXXFLAGS -D_LARGEFILE64_SOURCE"

mkdir -p path
cp $(command -v gtar) path/tar
export PATH="$PWD/path:$PATH"

case "$(uname)" in
    Linux) JOBS="$(nproc)" ;;
    FreeBSD | Darwin | OpenBSD) JOBS="$(sysctl -n hw.ncpu)" ;;
esac

if kiss list musl; then
    sed "s/ctypes.util.find_library('c')/'libc.so'/" \
        rpython/rlib/clibffi.py > _
    mv -f _ rpython/rlib/clibffi.py

    sed -E "s~(include <unistd.h>)~\1\n# include <sys/time.h>~" \
        pypy/module/cpyext/include/Python.h > _
    mv -f _ pypy/module/cpyext/include/Python.h

    sed -E "s~(if declare_as_extern):$~\1 and name not in ['stdin', 'stdout', 'stderr']:~" \
        rpython/rtyper/lltypesystem/rffi.py > _
    mv -f _ rpython/rtyper/lltypesystem/rffi.py
fi

cd pypy/goal/
if command -v pypy2; then
    pypy2 ../../rpython/bin/rpython --opt=jit --make-jobs "$JOBS" --shared targetpypystandalone
else
    python2 ../../rpython/bin/rpython --opt=jit --make-jobs "$JOBS" --shared targetpypystandalone
fi
#PYTHONPATH=../.. ./pypy3-c ../../lib_pypy/pypy_tools/build_cffi_imports.py
cd "$OLDPWD"

# _ssl is currently broken
if command -v pypy2; then
    pypy2 pypy/tool/release/package.py --without-_ssl --archive-name pypy3 --targetdir .
else
    python2 pypy/tool/release/package.py --without-_ssl --archive-name pypy3 --targetdir .
fi
mkdir -p "$1/opt"
tar xvf pypy3.tar.bz2 -C "$1/opt"

mkdir -p "$1/usr/bin/"
ln -s "/opt/pypy3/bin/pypy3"         "$1/usr/bin/pypy3"
ln -s "/opt/pypy3/bin/python"        "$1/usr/bin/python"
ln -s "/opt/pypy3/bin/python3"       "$1/usr/bin/python3"
ln -s "/opt/pypy3/bin/libpypy3-c.so" "$1/usr/bin/libpypy3-c.so"
