#!/bin/sh -e

patch -p1 < no-uuid.patch

# Don't build tests.
sed "/subdir('tests')/d" data/meson.build > _
mv -f _ data/meson.build

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddep11=false \
    -Dman=false \
    -Dstemmer=false \
    -Dintrospection=false \
    -Drpm=false \
    output

ninja -C output
ninja -C output install
