#!/bin/sh -e

rm -rf pkgs/sqlite3*

./unix/configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-threads \
    --enable-64bit

make INSTALL_ROOT="$1" install install-private-headers
ln -sf "tclsh${2%.*}"     "$1/usr/bin/tclsh"
ln -sf "libtcl${2%.*}.so" "$1/usr/lib/libtcl.so"

install -Dm644 unix/tcl.m4 -t "$1/usr/share/aclocal"

tdbcver=tdbc1.1.3
sed -e "s#$PWD/tcl$2/unix/pkgs/$tdbcver#/usr/lib/$tdbcver#" \
    -e "s#$PWD/tcl$2/pkgs/$tdbcver/generic#/usr/include#" \
    -e "s#$PWD/tcl$2/pkgs/$tdbcver/library#/usr/lib/tcl${2%.*}#" \
    -e "s#$PWD/tcl$2/pkgs/$tdbcver#/usr/include#" \
    "$1/usr/lib/$tdbcver/tdbcConfig.sh" > _
mv -f _ "$1/usr/lib/$tdbcver/tdbcConfig.sh"

itclver=itcl4.2.2
sed -e "s#$PWD/tcl$2/unix/pkgs/$itclver#/usr/lib/$itclver#" \
    -e "s#$PWD/tcl$2/pkgs/$itclver/generic#/usr/include#" \
    -e "s#$PWD/tcl$2/pkgs/$itclver#/usr/include#" \
    "$1/usr/lib/$itclver/itclConfig.sh" > _
mv -f _ "$1/usr/lib/$itclver/itclConfig.sh"
