#!/bin/sh -e

export DESTDIR="$1"

mk() {
    make \
        CFLAGS="$CFLAGS -fPIC -rdynamic -Iinclude -L." \
        LDFLAGS="$LDFLAGS -L." \
        PREFIX=/usr \
        "$@"
}

mk libcyclone.a
mk cyclone
mk icyc-c
mk
mk install
