#!/bin/sh -e

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dbuildtype=release \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexamples=disabled \
    . output

ninja -C output
ninja -C output install
