#!/bin/sh -e

: > tests/meson.build

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Dbuildtype=release \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexamples=disabled \
    output

ninja -C output
ninja -C output install
