#!/bin/sh -e

sed "s/-lstdc++/-stdlib=libstdc++/g" configure > _
mv -f _ configure
chmod +x configure

# Last 2 configure options can be optional
CFLAGS="$CFLAGS -no-pie" ./configure \
    --enable-shared \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --with-gmp

make
make compiler
make DESTDIR="$1" install
