#!/bin/sh -e

export DESTDIR="$1"

# TODO Cleanup non-libgccjit items.

# Do not use lib64 by default.
sed '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64 > _
mv -f _ gcc/gcc/config/i386/t-linux64
sed 's/lib64/lib/' gcc/gcc/config/i386/linux64.h > _
mv -f _ gcc/gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

../gcc/configure \
    libat_cv_have_ifunc=no \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --mandir=/usr/share/man \
    --disable-fixed-point \
    --disable-libada \
    --disable-libquadmath \
    --disable-libsanitizer \
    --disable-libssp \
    --disable-libvtv \
    --disable-lto \
    --disable-multilib \
    --disable-nls \
    --disable-symvers \
    --disable-werror \
    --enable-__cxa_atexit \
    --enable-checking=release \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-host-shared \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-languages=jit \
    --without-included-gettext \
    --with-zstd=no \
    --with-system-zlib \
    --build=x86_64-pc-linux-musl \
    --disable-bootstrap

make
make -C gcc install

# Remove unnecessary gcc files.
rm -rf "${1:?}/usr/bin" \
       "${1:?}/usr/lib/gcc" \
       "${1:?}/usr/libexec" \
       "${1:?}/usr/share/man"

# Remove info pages other than libgccjit
find "$1/usr/share/info" -type f ! -name libgccjit.info -exec rm -f {} +
