#!/bin/sh -e

if command -v nim; then
    nim_exe="$(command -v nim)"
else
    # Bootstrap nim.
    cd csources
    # Build nim source files
    sh ./build.sh
    cd "$OLDPWD"

    nim_exe="$PWD/bin/nim"
fi
# Build a release version of the "koch" maintenance program
$nim_exe compile --skipUserCfg --skipParentCfg --hints:off koch

# Build a release version of the nim compiler
./koch boot -d:release --skipUserCfg --skipParentCfg --hints:off

# Build nimsuggest, nimgrep, and nimpretty
./koch tools --skipUserCfg --skipParentCfg --hints:off

# Build nimrtl.nim
cd lib
$nim_exe c --app:lib -d:createNimRtl -d:release nimrtl.nim
cd "$OLDPWD"

mkdir -p \
    "$1/usr/bin/" \
    "$1/etc/nim/" \
    "$1/usr/lib/nim/"

cp -a lib/*    "$1/usr/lib/nim"
cp -a compiler "$1/usr/lib/nim"

mv -f compiler.nimble "$1/usr/lib/nim/compiler"
cp lib/libnimrtl.so "$1/usr/lib/libnimrtl.so"

cp config/* "$1/etc/nim/"
cp bin/*    "$1/usr/bin/"

# Workaround Nim's nonstandard header file placement
# (https://bugs.archlinux.org/task/50252)
mkdir -p "$1/usr/include/"
cp lib/*.h "$1/usr/include"

# Nimble looks for nimscriptapi.nim in /usr/bin/nimblepkg/, of all places
mkdir -p "$1/usr/share/nimble"

# Copy everything to the right folder
cp -r dist/nimble/src/nimblepkg "$1/usr/share/nimble"

# Link the two folders
ln -s "/usr/share/nimble/" "$1/usr/bin/nimblepkg"
