#!/bin/sh -e

ver="$(echo "$2" | cut -d'+' -f1)"

mv kernel-x86_64-fedora.config .config

if command -v ccache; then
    export PATH="/usr/lib/ccache/bin:$PATH"
fi

# Remove pahole dependency
sed "/CONFIG_DEBUG_INFO_BTF/d" .config > _
mv -f _ .config

patch -p1 < kernel-no-perl.patch

make olddefconfig
make -j "$(nproc)"
make INSTALL_MOD_PATH="$1/usr" modules_install

mkdir -p "$1/boot"
cp arch/x86/boot/bzImage "$1/boot/vmlinuz-$ver"
cp System.map            "$1/boot/System.map-$ver"
cp .config               "$1/boot/Config-$ver"
