#!/bin/sh -e
mk() {
    cmake -B build \
        -DBUILD_CONFIG=mysql_release \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSYSCONFDIR=/etc \
        -DSYSCONF2DIR=/etc/my.cnf.d \
        -DMYSQL_DATADIR=/var/lib/mysql \
        -DMYSQL_UNIX_ADDR=/var/run/mysqld/mysqld.sock \
        -DDEFAULT_CHARSET=utf8mb4 \
        -DDEFAULT_COLLATION=utf8mb4_general_ci \
        -DENABLED_LOCAL_INFILE=ON \
        -DINSTALL_MANDIR=/usr/share/man \
        -DINSTALL_PLUGINDIR=/usr/lib/mariadb/plugin \
        -DINSTALL_SCRIPTDIR=/usr/bin \
        -DINSTALL_INCLUDEDIR=/usr/include/mysql \
        -DINSTALL_DOCREADMEDIR=/usr/share/doc/mariadb \
        -DINSTALL_SUPPORTFILESDIR=/usr/share/mariadb \
        -DINSTALL_MYSQLSHAREDIR=/usr/share/mariadb \
        -DINSTALL_DOCDIR=/usr/share/doc/mariadb \
        -DTMPDIR=/var/tmp \
        -DCONNECT_WITH_MYSQL=ON \
        -DCONNECT_WITH_LIBXML2=system \
        -DCONNECT_WITH_ODBC=NO \
        -DCONNECT_WITH_JDBC=NO \
        -DPLUGIN_ARCHIVE=YES \
        -DPLUGIN_ARIA=YES \
        -DPLUGIN_BLACKHOLE=YES \
        -DPLUGIN_CASSANDRA=NO \
        -DPLUGIN_CSV=YES \
        -DPLUGIN_MYISAM=YES \
        -DPLUGIN_MROONGA=NO \
        -DPLUGIN_OQGRAPH=NO \
        -DPLUGIN_PARTITION=YES \
        -DPLUGIN_ROCKSDB=YES \
        -DPLUGIN_SPHINX=NO \
        -DPLUGIN_TOKUDB=NO \
        -DPLUGIN_AUTH_PAM=NO \
        -DPLUGIN_AUTH_PAM_CLIENT=OFF \
        -DPLUGIN_AUTH_GSSAPI=NO \
        -DPLUGIN_AUTH_GSSAPI_CLIENT=OFF \
        -DPLUGIN_CRACKLIB_PASSWORD_CHECK=NO \
        -DWITH_ASAN=OFF \
        -DWITH_EMBEDDED_SERVER=ON \
        -DWITH_EXTRA_CHARSETS=complex \
        -DWITH_INNODB_BZIP2=OFF \
        -DWITH_INNODB_LZ4=OFF \
        -DWITH_INNODB_LZMA=ON \
        -DWITH_INNODB_LZO=OFF \
        -DWITH_INNODB_SNAPPY=OFF \
        -DWITH_ROCKSDB_BZIP2=OFF \
        -DWITH_ROCKSDB_JEMALLOC=OFF \
        -DWITH_ROCKSDB_LZ4=OFF \
        -DWITH_ROCKSDB_ZSTD=OFF \
        -DWITH_ROCKSDB_SNAPPY=OFF \
        -DWITH_JEMALLOC=NO \
        -DWITH_LIBARCHIVE=system \
        -DWITH_LIBNUMA=NO \
        -DWITH_LIBWRAP=OFF \
        -DWITH_LIBWSEP=OFF \
        -DWITH_MARIABACKUP=ON \
        -DWITH_PCRE=system \
        -DWITH_READLINE=OFF \
        -DWITH_SYSTEMD=no \
        -DWITH_SSL=system \
        -DWITH_VALGRIND=OFF \
        -DWITH_ZLIB=system \
        -DSKIP_TESTS=ON \
        -DIGNORE_AIO_CHECK=ON

    cmake --build build
    cmake --install build
}

# If mold is the system linker, switch it.
if [ "$(kiss owns /usr/bin/ld)" = "mold" ]; then
    kiss alternatives | grep '/usr/bin/ld' | kiss a -
    mk
    kiss alternatives mold '/usr/bin/ld'
else
    mk
fi

mkdir -p "$1/etc/my.cnf.d"
mkdir -p "$1/var/lib/mysql"
mkdir -p "$1/usr/lib/mariadb/plugin"

chmod 777 "$1/var/lib/mysql"

cat > "$1/etc/my.cnf" <<- EOF
# This group is read both both by the client and the server
# use it for options that affect everything
[client-server]

# This group is read by the server
[mysqld]

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

# include all files from the config directory
!includedir /etc/my.cnf.d
EOF

cat > "$1/etc/my.cnf.d/mariadb-server.cnf" <<- EOF
#
# These groups are read by MariaDB server.
# Use it for options that only the server (but not clients) should see

# this is read by the standalone daemon and embedded servers
[server]

# this is only for the mysqld standalone daemon
[mysqld]
skip-networking

# Galera-related settings
[galera]
# Mandatory settings
#wsrep_on=ON
#wsrep_provider=
#wsrep_cluster_address=
#binlog_format=row
#default_storage_engine=InnoDB
#innodb_autoinc_lock_mode=2
#
# Allow server to accept connections on all interfaces.
#
#bind-address=0.0.0.0
#
# Optional setting
#wsrep_slave_threads=1
#innodb_flush_log_at_trx_commit=0

# this is only for embedded server
[embedded]

# This group is only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]

# This group is only read by MariaDB-10.5 servers.
# If you use the same .cnf file for MariaDB of different versions,
# use this group for options that older servers don't understand
[mariadb-10.5]
EOF
