#!/bin/sh -e

export DESTDIR="$1"

# Remove muon incompatible option.
sed "s/'build.c_std=c99',//" meson.build > _
mv -f _ meson.build

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install
