#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix="/usr" \
    --with-system-libffi \
    --disable-ld-override

sed -e 's/unknown/pc/g' llvm-targets > _
mv -f _ llvm-targets

./hadrian/build install --prefix="/usr" -j --flavour=quickest+no_profiled_libs --docs=none --skip-depends
