#!/bin/sh -e

export DESTDIR="$1"

sed \
    -e "s/__atomic_compare_exchange((p), (o), (n))/__atomic_compare_exchange_db((p), (o), (n))/" \
    -e "s/static inline int __atomic_compare_exchange(/static inline int __atomic_compare_exchange_db(/" \
    src/dbinc/atomic.h > _
mv -f _ src/dbinc/atomic.h

cd build_unix
  ../dist/configure \
    --prefix=/usr \
    --enable-compat185 \
    --enable-shared \
    --enable-static \
    --enable-cxx \
    --enable-dbm \
    --disable-stl \
    --disable-tcl \
    --disable-gui \
    --disable-slices \
    --disable-test \
    --disable-localization

make LIBSO_LIBS=-lpthread DESTDIR="$1"

make DESTDIR="$1" install
