#!/bin/sh -e

CFLAGS="$CFLAGS -fPIC -fcommon"
EXTRA_CONF=""
for p in mariadb postgresql sqlite cyrus-sasl; do
    if kiss l "$p"; then
        case "$p" in
            mariadb)
                CFLAGS="$CFLAGS -DHAS_MYSQL -I/usr/include/mysql "
                EXTRA_CONF="$EXTRA_CONF AUXLIBS_MYSQL=\"$(pkgconf --libs mariadb)\" "
                ;;
            postgresql)
                CFLAGS="$CFLAGS -DHAS_PGSQL -I/usr/include/postgresql "
                EXTRA_CONF="$EXTRA_CONF AUXLIBS_PGSQL=\"$(pkgconf --libs libpq)\" "
                ;;
            sqlite)
                CFLAGS="$CFLAGS -DHAS_SQLITE "
                EXTRA_CONF="$EXTRA_CONF AUXLIBS_SQLITE=\"$(pkgconf --libs sqlite3)\" "
                ;;
            cyrus-sasl)
                CFLAGS="$CFLAGS -DUSE_CYRUS_SASL -I/usr/include/sasl "
                ;;
        esac
    fi
done

CFLAGS="$CFLAGS
-DUSE_TLS
-DDEF_COMMAND_DIR=\"/usr/bin/\"
-DDEF_DAEMON_DIR=\"/usr/lib/postfix/bin\"
-DDEF_SENDMAIL_PATH=\"/usr/bin/sendmail\"
-DDEF_MANPAGE_DIR=\"/usr/share/man\"
"

make makefiles \
    DEBUG='' \
    shared=yes \
    dynamicmaps=yes \
    CCARGS="$CFLAGS" \
    AUXLIBS="$(pkgconf --libs openssl libsasl2)" \
    OPT="${CFLAGS} ${CPPFLAGS} ${LDFLAGS}" \
    $EXTRA_CONF

make

sh postfix-install -non-interactive install_root="$1"
