#!/bin/sh -e

: > nostrip

for p in *.patch; do
    patch -p1 < "$p"
done

./configure \
    --prefix=/usr \
    --program-suffix=3 \
    --enable-posix \
    --disable-error-on-warning \
    --disable-lto \
    --disable-rpath

make
make install
