#!/bin/sh -e

: > nostrip

./configure \
    --prefix=/usr \
    --program-suffix=3 \
    --enable-posix \
    --disable-error-on-warning \
    --enable-jit \
    --enable-netowrking \
    --disable-nls \
    --enable-regex \
    --with-threads

make -j1
make -j1 install
