#!/bin/sh -e

kiss list libedit && {
    sed "s/-lreadline/-ledit/" configure > _
    mv -f _ configure
    chmod +x configure
}

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --enable-static

make
make DESTDIR="$1" install
