#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --disable-valadoc

make
make install

# Remove unnecessary stuff.
find "$1" -name "*.la" -exec rm -rf {} +

# Directory is not needed.
rm -rf "$1/usr/share/devhelp"
