#!/bin/sh -e
export CFLAGS="$CFLAGS -w "
export CXXFLAGS="$CXXFLAGS -w "
./otp_build autoconf
./configure \
	--prefix=/usr \
	--disable-hipe
sed -i -e '/LDFLAGS =/s/=/+=/' lib/odbc/c_src/*/Makefile
make
make install
#make install-docs
