#!/bin/sh -e
export CFLAGS="$CFLAGS -w "
export CXXFLAGS="$CXXFLAGS -w "
./otp_build autoconf
./configure \
    --prefix=/usr
for d in lib/odbc/c_src/*/; do
    sed '/LDFLAGS =/s/=/+=/' "$d/Makefile" > _
    mv -f _ "$d/Makefile"
done
make
make install
