#!/bin/sh -e
./configure \
    --prefix=/usr \
    --sysconfdir=/etc
sed '/-Werror/d' config.mk > _
mv -f _ config.mk
make
make install

kiss list glibc && libc=""
kiss list musl && libc="musl/"

printf "repository=https://repo-default.voidlinux.org/current/%s" "${libc}" \
    > "$1/usr/share/xbps.d/00-repository-main.conf"
