#!/bin/sh -e

tclver="${2%.*}"
./unix/configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-threads \
    --disable-rpath \
    --enable-64bit

make
make INSTALL_ROOT="$1" install install-private-headers

ln -sf "wish${tclver%.*}"     "$1/usr/bin/wish"
ln -sf "libtk${tclver%.*}.so" "$1/usr/lib/libtk.so"

for dir in compat generic generic/ttk unix; do
    install -dm755   "$1/usr/include/tk-private/$dir"
    install -m644 -t "$1/usr/include/tk-private/$dir" "$dir"/*.h
done

# remove buildroot traces
sed -e "s#$PWD/tk${tclver}/unix#/usr/lib#" \
    -e "s#$PWD/tk${tclver}#/usr/include#" \
    "$1/usr/lib/tkConfig.sh" > _
mv -f _ "$1/usr/lib/tkConfig.sh"
